require: rubocop-rails

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - cypress

Rails/I18nLocaleTexts:
  Enabled: false

AllCops:
  NewCops: enable
