name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn

      - name: Build CSS
        run: yarn build:css

      - name: Build JS
        run: yarn build:js

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn

      - name: ESLint
        run: yarn run lint

      - name: Rubocop
        run: bundle exec rubocop

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn

      - name: Typecheck
        run: yarn run typecheck

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Minitest
        run: bundle exec rails test

      - name: RSpec
        run: bundle exec rspec

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn

      - name: Yarn Build
        run: yarn build:all

      - name: Cypress run
        env:
          RAILS_ENV: 'cypress'
          SECRET_KEY_BASE: DUMMY
        run: bundle exec rake cypress:run

      # upload screenshots and image diff file if tests fail
      - name: Save screenshots
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            tmp/cypress_snapshots
            tmp/cypress_videos
